"""empty message

Revision ID: 1a09dfd36652
Revises: 83ec80326617
Create Date: 2025-07-10 10:09:42.084522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a09dfd36652'
down_revision = '83ec80326617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('must_change_password',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('is_super_admin')

    # ### end Alembic commands ###
