"""add_must_change_password_column

Revision ID: 83ec80326617
Revises: 3663a4b271fa
Create Date: 2025-07-09 22:54:39.967108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ec80326617'
down_revision = '3663a4b271fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero agregamos la columna como nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))
    
    # Actualizamos todos los registros existentes con valor por defecto
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET must_change_password = 1 WHERE must_change_password IS NULL"))
    
    # Ahora hacemos la columna NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('must_change_password', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
