"""Add is_super_admin field to users

Revision ID: add_super_admin
Revises: 1a09dfd36652
Create Date: 2025-07-10 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_super_admin'
down_revision = '1a09dfd36652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE users SET is_super_admin = 0 WHERE is_super_admin IS NULL")
    
    # Make column non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')
    # ### end Alembic commands ###
