"""add_user_privileges_and_profile_fields

Revision ID: c46770066e3e
Revises: eaf590dbb514
Create Date: 2025-07-10 11:25:05.155264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46770066e3e'
down_revision = 'eaf590dbb514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hire_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('can_view_calendar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_upload_photos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_photos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_time_tracking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_own_reports', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_all_reports', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_time_entries', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_upload_documents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_own_documents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_all_documents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_export_data', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('can_export_data')
        batch_op.drop_column('can_manage_users')
        batch_op.drop_column('can_view_all_documents')
        batch_op.drop_column('can_view_own_documents')
        batch_op.drop_column('can_upload_documents')
        batch_op.drop_column('can_manage_time_entries')
        batch_op.drop_column('can_view_all_reports')
        batch_op.drop_column('can_view_own_reports')
        batch_op.drop_column('can_time_tracking')
        batch_op.drop_column('can_manage_photos')
        batch_op.drop_column('can_upload_photos')
        batch_op.drop_column('can_view_calendar')
        batch_op.drop_column('hire_date')
        batch_op.drop_column('position')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
