"""add_maintenance_and_update_log_models

Revision ID: eaf590dbb514
Revises: add_super_admin
Create Date: 2025-07-10 10:31:13.400137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf590dbb514'
down_revision = 'add_super_admin'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_by', sa.String(length=80), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.String(length=80), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('git_commit_before', sa.String(length=40), nullable=True),
    sa.Column('git_commit_after', sa.String(length=40), nullable=True),
    sa.Column('migration_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_logs')
    op.drop_table('maintenance_mode')
    # ### end Alembic commands ###
